# Generated by Django 5.2.4 on 2025-07-04 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FundsApp', '0001_initial'),
        ('MembersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the contribution.', max_digits=15)),
                ('contribution_date', models.DateField(default=django.utils.timezone.now, help_text='The date the contribution was received.')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('online', 'Online Transfer/Card'), ('mobile_money', 'Mobile Money (e.g., M-Pesa)'), ('other', 'Other')], default='cash', help_text='The method used for this contribution.', max_length=20)),
                ('check_number', models.CharField(blank=True, help_text="Check number, if payment method is 'Check'.", max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID for online or mobile money payments.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text="Any additional notes about the contribution (e.g., 'anonymous cash donation').", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(help_text='The member/donor who made this contribution.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='MembersApp.member')),
                ('fund', models.ForeignKey(help_text='The fund to which this contribution is directed.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='FundsApp.fund')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-contribution_date', 'donor__name'],
            },
        ),
    ]
