# Generated by Django 4.2.7 on 2025-07-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContributionsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text="Upload your church's logo image", upload_to='church_logos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one logo should be active at a time.')),
            ],
            options={
                'verbose_name': 'Church Logo',
                'verbose_name_plural': 'Church Logos',
            },
        ),
    ]
