# Generated by Django 5.2.3 on 2025-07-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContributionsApp', '0002_churchlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChurchLogo',
        ),
    ]
