# Generated by Django 5.2.4 on 2025-07-04 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FundsApp', '0001_initial'),
        ('MembersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_amount', models.DecimalField(decimal_places=2, help_text='The total amount pledged.', max_digits=15)),
                ('pledge_date', models.DateField(default=django.utils.timezone.now, help_text='The date the pledge was made.')),
                ('fulfillment_frequency', models.CharField(choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('other', 'Other')], default='one_time', help_text="How often the donor intends to fulfill the pledge (e.g., 'Weekly', 'One-time').", max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='The date when the pledge fulfillment period starts (optional).', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date when the pledge fulfillment period is expected to end (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(help_text='The member/donor who made this pledge.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='MembersApp.member')),
                ('fund', models.ForeignKey(help_text='The fund to which the pledge is directed.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='FundsApp.fund')),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
                'ordering': ['-pledge_date'],
            },
        ),
    ]
