# Generated by Django 5.2.4 on 2025-07-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the fund (e.g., 'General Tithes', 'Thanksgiving Offering').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the fund's purpose.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the fund is currently active and accepting contributions.')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Target amount for this fund/campaign (e.g., for a special offering like Thanksgiving). Set to 0 if no specific target.', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'ordering': ['name'],
            },
        ),
    ]
