# Generated by Django 5.2.4 on 2025-07-04 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the church member or donor.', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address of the member. Must be unique if provided.', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the member.', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the member.', null=True)),
                ('member_id', models.CharField(blank=True, help_text='Unique identifier for the member, e.g., envelope number or internal ID.', max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the member is currently active in the church.')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, help_text='Date the member joined or was added to the system.')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the member (e.g., spiritual gifts, ministry involvement).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_head', models.ForeignKey(blank=True, help_text='Links to the head of the family, if this member is part of a family group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='MembersApp.member')),
            ],
            options={
                'verbose_name': 'Member / Donor',
                'verbose_name_plural': 'Members / Donors',
                'ordering': ['name'],
            },
        ),
    ]
